; JOCKY compiled output — CASE-2026-0417
; Operator: J.Sharma  Target: WIN-MACHINE-04  Mode: remote
; Obfuscated: True
; Generated by JOCKY IR generator v0.1.0

; ModuleID = "jocky_CASE_2026_0417"
target triple = "unknown-unknown-unknown"
target datalayout = ""

declare external i32 @"jocky_acquire_process_list"()

declare external i32 @"jocky_acquire_memory_region"(i32 %".1", i64 %".2")

declare external i32 @"jocky_acquire_cpu_registers"()

declare external i32 @"jocky_acquire_connections"()

declare external i32 @"jocky_acquire_dns_cache"()

declare external i32 @"jocky_capture_traffic"(i32 %".1", i8* %".2")

declare external i32 @"jocky_inspect_registry"(i8* %".1")

declare external i32 @"jocky_inspect_services"(i8* %".1")

declare external i32 @"jocky_inspect_startup_items"()

declare external i32 @"jocky_inspect_file_metadata"(i8* %".1")

declare external i32 @"jocky_inspect_recent_files"(i32 %".1")

declare external i32 @"jocky_hash_file"(i8* %".1")

define i32 @"jocky_main"()
{
entry:
  br label %"pred_0"
pred_0:
  %"ctr_0" = load i32, i32* @"jocky_opaque_counter"
  %"ctr_p1_0" = add i32 %"ctr_0", 1
  %"prod_0" = mul i32 %"ctr_0", %"ctr_p1_0"
  %"lsb_0" = and i32 %"prod_0", 1
  %"pred_0.1" = icmp eq i32 %"lsb_0", 0
  br i1 %"pred_0.1", label %"op_0", label %"junk_0"
pred_1:
  %"ctr_1" = load i32, i32* @"jocky_opaque_counter"
  %"ctr_p1_1" = add i32 %"ctr_1", 1
  %"prod_1" = mul i32 %"ctr_1", %"ctr_p1_1"
  %"lsb_1" = and i32 %"prod_1", 1
  %"pred_1.1" = icmp eq i32 %"lsb_1", 0
  br i1 %"pred_1.1", label %"op_1", label %"junk_1"
pred_2:
  %"ctr_2" = load i32, i32* @"jocky_opaque_counter"
  %"ctr_p1_2" = add i32 %"ctr_2", 1
  %"prod_2" = mul i32 %"ctr_2", %"ctr_p1_2"
  %"lsb_2" = and i32 %"prod_2", 1
  %"pred_2.1" = icmp eq i32 %"lsb_2", 0
  br i1 %"pred_2.1", label %"op_2", label %"junk_2"
pred_3:
  %"ctr_3" = load i32, i32* @"jocky_opaque_counter"
  %"ctr_p1_3" = add i32 %"ctr_3", 1
  %"prod_3" = mul i32 %"ctr_3", %"ctr_p1_3"
  %"lsb_3" = and i32 %"prod_3", 1
  %"pred_3.1" = icmp eq i32 %"lsb_3", 0
  br i1 %"pred_3.1", label %"op_3", label %"junk_3"
pred_4:
  %"ctr_4" = load i32, i32* @"jocky_opaque_counter"
  %"ctr_p1_4" = add i32 %"ctr_4", 1
  %"prod_4" = mul i32 %"ctr_4", %"ctr_p1_4"
  %"lsb_4" = and i32 %"prod_4", 1
  %"pred_4.1" = icmp eq i32 %"lsb_4", 0
  br i1 %"pred_4.1", label %"op_4", label %"junk_4"
pred_5:
  %"ctr_5" = load i32, i32* @"jocky_opaque_counter"
  %"ctr_p1_5" = add i32 %"ctr_5", 1
  %"prod_5" = mul i32 %"ctr_5", %"ctr_p1_5"
  %"lsb_5" = and i32 %"prod_5", 1
  %"pred_5.1" = icmp eq i32 %"lsb_5", 0
  br i1 %"pred_5.1", label %"op_5", label %"junk_5"
pred_6:
  %"ctr_6" = load i32, i32* @"jocky_opaque_counter"
  %"ctr_p1_6" = add i32 %"ctr_6", 1
  %"prod_6" = mul i32 %"ctr_6", %"ctr_p1_6"
  %"lsb_6" = and i32 %"prod_6", 1
  %"pred_6.1" = icmp eq i32 %"lsb_6", 0
  br i1 %"pred_6.1", label %"op_6", label %"junk_6"
pred_7:
  %"ctr_7" = load i32, i32* @"jocky_opaque_counter"
  %"ctr_p1_7" = add i32 %"ctr_7", 1
  %"prod_7" = mul i32 %"ctr_7", %"ctr_p1_7"
  %"lsb_7" = and i32 %"prod_7", 1
  %"pred_7.1" = icmp eq i32 %"lsb_7", 0
  br i1 %"pred_7.1", label %"op_7", label %"junk_7"
pred_8:
  %"ctr_8" = load i32, i32* @"jocky_opaque_counter"
  %"ctr_p1_8" = add i32 %"ctr_8", 1
  %"prod_8" = mul i32 %"ctr_8", %"ctr_p1_8"
  %"lsb_8" = and i32 %"prod_8", 1
  %"pred_8.1" = icmp eq i32 %"lsb_8", 0
  br i1 %"pred_8.1", label %"op_8", label %"junk_8"
pred_9:
  %"ctr_9" = load i32, i32* @"jocky_opaque_counter"
  %"ctr_p1_9" = add i32 %"ctr_9", 1
  %"prod_9" = mul i32 %"ctr_9", %"ctr_p1_9"
  %"lsb_9" = and i32 %"prod_9", 1
  %"pred_9.1" = icmp eq i32 %"lsb_9", 0
  br i1 %"pred_9.1", label %"op_9", label %"junk_9"
pred_10:
  %"ctr_10" = load i32, i32* @"jocky_opaque_counter"
  %"ctr_p1_10" = add i32 %"ctr_10", 1
  %"prod_10" = mul i32 %"ctr_10", %"ctr_p1_10"
  %"lsb_10" = and i32 %"prod_10", 1
  %"pred_10.1" = icmp eq i32 %"lsb_10", 0
  br i1 %"pred_10.1", label %"op_10", label %"junk_10"
pred_11:
  %"ctr_11" = load i32, i32* @"jocky_opaque_counter"
  %"ctr_p1_11" = add i32 %"ctr_11", 1
  %"prod_11" = mul i32 %"ctr_11", %"ctr_p1_11"
  %"lsb_11" = and i32 %"prod_11", 1
  %"pred_11.1" = icmp eq i32 %"lsb_11", 0
  br i1 %"pred_11.1", label %"op_11", label %"junk_11"
op_0:
  %".4" = call i32 @"jocky_acquire_process_list"()
  br label %"pred_1"
op_1:
  %".8" = call i32 @"jocky_acquire_memory_region"(i32 1044, i64 4096)
  br label %"pred_2"
op_2:
  %".12" = call i32 @"jocky_acquire_cpu_registers"()
  br label %"pred_3"
op_3:
  %".16" = call i32 @"jocky_acquire_connections"()
  br label %"pred_4"
op_4:
  %".20" = call i32 @"jocky_acquire_dns_cache"()
  br label %"pred_5"
op_5:
  %".24" = getelementptr inbounds [5 x i8], [5 x i8]* @".str.0", i32 0, i32 0
  %".25" = call i32 @"jocky_capture_traffic"(i32 30, i8* %".24")
  br label %"pred_6"
op_6:
  %".29" = getelementptr inbounds [51 x i8], [51 x i8]* @".str.1", i32 0, i32 0
  %".30" = call i32 @"jocky_inspect_registry"(i8* %".29")
  br label %"pred_7"
op_7:
  %".34" = getelementptr inbounds [8 x i8], [8 x i8]* @".str.2", i32 0, i32 0
  %".35" = call i32 @"jocky_inspect_services"(i8* %".34")
  br label %"pred_8"
op_8:
  %".39" = call i32 @"jocky_inspect_startup_items"()
  br label %"pred_9"
op_9:
  %".43" = getelementptr inbounds [29 x i8], [29 x i8]* @".str.3", i32 0, i32 0
  %".44" = call i32 @"jocky_hash_file"(i8* %".43")
  br label %"pred_10"
op_10:
  %".48" = getelementptr inbounds [29 x i8], [29 x i8]* @".str.4", i32 0, i32 0
  %".49" = call i32 @"jocky_inspect_file_metadata"(i8* %".48")
  br label %"pred_11"
op_11:
  %".53" = call i32 @"jocky_inspect_recent_files"(i32 20)
  br label %"exit"
junk_0:
  %"junk_0.1" = call i32 @"jocky_acquire_dns_cache"()
  br label %"pred_1"
junk_1:
  %"junk_1.1" = call i32 @"jocky_acquire_cpu_registers"()
  br label %"pred_2"
junk_2:
  %"junk_2.1" = call i32 @"jocky_acquire_process_list"()
  br label %"pred_3"
junk_3:
  %"junk_3.1" = call i32 @"jocky_acquire_dns_cache"()
  br label %"pred_4"
junk_4:
  %"junk_4.1" = call i32 @"jocky_acquire_process_list"()
  br label %"pred_5"
junk_5:
  %"junk_5.1" = call i32 @"jocky_inspect_startup_items"()
  br label %"pred_6"
junk_6:
  %"junk_6.1" = call i32 @"jocky_acquire_connections"()
  br label %"pred_7"
junk_7:
  %"junk_7.1" = call i32 @"jocky_acquire_cpu_registers"()
  br label %"pred_8"
junk_8:
  %"junk_8.1" = call i32 @"jocky_acquire_connections"()
  br label %"pred_9"
junk_9:
  %"junk_9.1" = call i32 @"jocky_acquire_process_list"()
  br label %"pred_10"
junk_10:
  %"junk_10.1" = call i32 @"jocky_acquire_connections"()
  br label %"pred_11"
junk_11:
  %"junk_11.1" = call i32 @"jocky_acquire_connections"()
  br label %"exit"
exit:
  ret i32 0
}

@"jocky_opaque_counter" = internal global i32 0
@".str.0" = internal constant [5 x i8] c"eth0\00"
@".str.1" = internal constant [51 x i8] c"HKLM\5cSoftware\5cMicrosoft\5cWindows\5cCurrentVersion\5cRun\00"
@".str.2" = internal constant [8 x i8] c"running\00"
@".str.3" = internal constant [29 x i8] c"C:\5cUsers\5csuspect\5cinvoice.pdf\00"
@".str.4" = internal constant [29 x i8] c"C:\5cUsers\5csuspect\5cinvoice.pdf\00"