; JOCKY compiled output — CASE-2026-0417
; Operator: J.Sharma  Target: WIN-MACHINE-04  Mode: remote
; Generated by JOCKY IR generator v0.1.0

; ModuleID = "jocky_CASE_2026_0417"
target triple = "unknown-unknown-unknown"
target datalayout = ""

declare external i32 @"jocky_acquire_process_list"()

declare external i32 @"jocky_acquire_memory_region"(i32 %".1", i64 %".2")

declare external i32 @"jocky_acquire_cpu_registers"()

declare external i32 @"jocky_acquire_connections"()

declare external i32 @"jocky_acquire_dns_cache"()

declare external i32 @"jocky_capture_traffic"(i32 %".1", i8* %".2")

declare external i32 @"jocky_inspect_registry"(i8* %".1")

declare external i32 @"jocky_inspect_services"(i8* %".1")

declare external i32 @"jocky_inspect_startup_items"()

declare external i32 @"jocky_inspect_file_metadata"(i8* %".1")

declare external i32 @"jocky_inspect_recent_files"(i32 %".1")

declare external i32 @"jocky_hash_file"(i8* %".1")

define i32 @"jocky_main"()
{
entry:
  %".2" = call i32 @"jocky_acquire_process_list"()
  %".3" = call i32 @"jocky_acquire_memory_region"(i32 1044, i64 4096)
  %".4" = call i32 @"jocky_acquire_cpu_registers"()
  %".5" = call i32 @"jocky_acquire_connections"()
  %".6" = call i32 @"jocky_acquire_dns_cache"()
  %".7" = getelementptr inbounds [5 x i8], [5 x i8]* @".str.0", i32 0, i32 0
  %".8" = call i32 @"jocky_capture_traffic"(i32 30, i8* %".7")
  %".9" = getelementptr inbounds [51 x i8], [51 x i8]* @".str.1", i32 0, i32 0
  %".10" = call i32 @"jocky_inspect_registry"(i8* %".9")
  %".11" = getelementptr inbounds [8 x i8], [8 x i8]* @".str.2", i32 0, i32 0
  %".12" = call i32 @"jocky_inspect_services"(i8* %".11")
  %".13" = call i32 @"jocky_inspect_startup_items"()
  %".14" = getelementptr inbounds [29 x i8], [29 x i8]* @".str.3", i32 0, i32 0
  %".15" = call i32 @"jocky_hash_file"(i8* %".14")
  %".16" = getelementptr inbounds [29 x i8], [29 x i8]* @".str.4", i32 0, i32 0
  %".17" = call i32 @"jocky_inspect_file_metadata"(i8* %".16")
  %".18" = call i32 @"jocky_inspect_recent_files"(i32 20)
  ret i32 0
}

@".str.0" = internal constant [5 x i8] c"eth0\00"
@".str.1" = internal constant [51 x i8] c"HKLM\5cSoftware\5cMicrosoft\5cWindows\5cCurrentVersion\5cRun\00"
@".str.2" = internal constant [8 x i8] c"running\00"
@".str.3" = internal constant [29 x i8] c"C:\5cUsers\5csuspect\5cinvoice.pdf\00"
@".str.4" = internal constant [29 x i8] c"C:\5cUsers\5csuspect\5cinvoice.pdf\00"