"""
JOCKY Forensic Language — LLVM IR Generator  (Phase 5)
=======================================================
Single responsibility: translate a validated JOCKY parse tree into
LLVM Intermediate Representation text.

No execution happens here — this is purely translation.
The IR forward-declares all forensic primitives as external C functions
and emits a jocky_main() that calls them in script order.

Chain of custody:
  .jky → parse → validate → generate_ir → .ll file
  → Clang → Windows PE or Linux ELF

Phase 12 provides the C implementations of the declared functions.
Phase 6 (CFG obfuscation) is not implemented in this project scope.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

import llvmlite.ir as ir
from lark import Tree

# ─── LLVM primitive types ─────────────────────────────────────────────────────

_i8  = ir.IntType(8)
_i32 = ir.IntType(32)
_i64 = ir.IntType(64)
_i8p = _i8.as_pointer()   # i8* — C string pointer (path, key, state, interface)
_ret = _i32                # all primitives return i32: 0 = success, non-zero = error

# ─── Script context ───────────────────────────────────────────────────────────

@dataclass
class _ScriptContext:
    """
    Per-script metadata built from the case block.
    Used for IR module naming and header comments only.
    Not passed to generated code at runtime.
    """
    case_id:  str
    operator: str
    target:   str
    mode:     str


def context_from_tree(tree: Tree) -> _ScriptContext:
    """
    Extract case header fields from the validated parse tree.
    Public so the CLI and any future pipeline stage can call it directly
    without importing interpreter.py.
    """
    case_block = next(tree.find_data("case_block"))
    return _ScriptContext(
        case_id  = _get_str_field(case_block, "id_field"),
        operator = _get_str_field(case_block, "operator_field"),
        target   = _get_str_field(case_block, "target_field"),
        mode     = _get_str_field(case_block, "mode_field"),
    )


# ─── Primitive signatures ─────────────────────────────────────────────────────
# Maps IR function name → [(param_name, ir_type), ...]
#
# This table is the single source of truth for the C ABI between
# the compiled JOCKY agent and the Phase 12 C primitives.
# Both sides must use identical names and types.
#
# Naming convention: jocky_{command}_{primitive}

_SIGS: dict[str, list[tuple[str, ir.Type]]] = {
    "jocky_acquire_process_list":  [],
    "jocky_acquire_memory_region": [("pid", _i32), ("size", _i64)],
    "jocky_acquire_cpu_registers": [],
    "jocky_acquire_connections":   [],
    "jocky_acquire_dns_cache":     [],
    "jocky_capture_traffic":       [("duration", _i32), ("interface", _i8p)],
    "jocky_inspect_registry":      [("key", _i8p)],
    "jocky_inspect_services":      [("state", _i8p)],
    "jocky_inspect_startup_items": [],
    "jocky_inspect_file_metadata": [("path", _i8p)],
    "jocky_inspect_recent_files":  [("count", _i32)],
    "jocky_hash_file":             [("path", _i8p)],
}


# ─── Public API ───────────────────────────────────────────────────────────────

def generate_ir(tree: Tree, context: _ScriptContext) -> str:
    """
    Generate LLVM IR text for a validated JOCKY parse tree.

    Parameters
    ----------
    tree : lark.Tree
        Must have already passed validate().
    context : _ScriptContext
        Built via context_from_tree(tree).

    Returns
    -------
    str
        Complete LLVM IR text. Write to a .ll file and compile with:
            clang -o output output.ll primitives.c
    """
    # Sanitise case_id for use as a module identifier (no hyphens)
    module_name = f"jocky_{context.case_id.replace('-', '_')}"
    module = ir.Module(name=module_name)

    # Declare all external forensic primitive functions (forward declarations).
    fn_refs = _declare_primitives(module)

    # Build jocky_main() — one call instruction per script operation, in order.
    _build_main(module, tree, fn_refs)

    # llvmlite produces the body; we prepend a human-readable header.
    header = (
        f"; JOCKY compiled output — {context.case_id}\n"
        f"; Operator: {context.operator}  "
        f"Target: {context.target}  Mode: {context.mode}\n"
        f"; Generated by JOCKY IR generator v0.1.0\n\n"
    )
    return header + str(module)


# ─── Primitive declarations ───────────────────────────────────────────────────

def _declare_primitives(module: ir.Module) -> dict[str, ir.Function]:
    """
    Emit `declare` statements for every external C primitive.

    Returns a dict mapping IR name → Function object so _build_main
    can call them without re-instantiating.
    """
    fn_refs: dict[str, ir.Function] = {}
    for fn_name, params in _SIGS.items():
        fn_type = ir.FunctionType(_ret, [ptype for _, ptype in params])
        fn = ir.Function(module, fn_type, name=fn_name)
        fn.linkage = "external"   # defined in Phase 12 C code, not here
        fn_refs[fn_name] = fn
    return fn_refs


# ─── Main function construction ───────────────────────────────────────────────

def _build_main(
    module:  ir.Module,
    tree:    Tree,
    fn_refs: dict[str, ir.Function],
) -> ir.Function:
    """
    Define `jocky_main()` with one call instruction per script operation.

    Operations are emitted in volatility order — the validator already
    enforced that, so the tree is walked top-to-bottom without re-sorting.
    """
    main_fn = ir.Function(module, ir.FunctionType(_i32, []), name="jocky_main")
    block   = main_fn.append_basic_block(name="entry")
    builder = ir.IRBuilder(block)

    # Shared counter for unique global string constant names within this module
    str_counter = [0]

    for section_block in tree.find_data("section_block"):
        for child in section_block.children:
            if isinstance(child, Tree) and child.data == "operation":
                _emit_call(builder, child, fn_refs, module, str_counter)

    builder.ret(ir.Constant(_i32, 0))
    return main_fn


# ─── Call emission ────────────────────────────────────────────────────────────

def _emit_call(
    builder:     ir.IRBuilder,
    operation:   Tree,
    fn_refs:     dict[str, ir.Function],
    module:      ir.Module,
    str_counter: list[int],
) -> None:
    """Translate one JOCKY operation node into a single IR call instruction."""
    command_str   = str(_first_tree_child(operation, "command").children[0])
    primitive_str = str(_first_tree_child(operation, "primitive").children[0])
    fn_name       = f"jocky_{command_str}_{primitive_str}"

    arglist_node: Tree | None = None
    for child in operation.children:
        if isinstance(child, Tree) and child.data == "arglist":
            arglist_node = child
            break

    args    = _extract_args(arglist_node)
    sig     = _SIGS.get(fn_name, [])
    ir_args = _args_to_ir(builder, args, sig, module, str_counter)

    builder.call(fn_refs[fn_name], ir_args)


# ─── Argument conversion ──────────────────────────────────────────────────────

def _args_to_ir(
    builder:     ir.IRBuilder,
    args:        dict,
    sig:         list[tuple[str, ir.Type]],
    module:      ir.Module,
    str_counter: list[int],
) -> list[ir.Value]:
    """
    Convert Python arg dict + declared signature into a list of IR values.

    For each declared parameter (in signature order):
      i8*  → internal global null-terminated string constant, GEP pointer
      i64  → ir.Constant(i64, value)
      i32  → ir.Constant(i32, value)
    Missing args default to 0 or empty string.
    """
    ir_values: list[ir.Value] = []
    for param_name, param_type in sig:
        raw = args.get(param_name)
        if param_type == _i8p:
            s = str(raw) if raw is not None else ""
            ir_values.append(_make_str_const(builder, module, s, str_counter))
        elif param_type == _i64:
            ir_values.append(ir.Constant(_i64, int(raw) if raw is not None else 0))
        else:  # _i32
            ir_values.append(ir.Constant(_i32, int(raw) if raw is not None else 0))
    return ir_values


def _make_str_const(
    builder:     ir.IRBuilder,
    module:      ir.Module,
    s:           str,
    counter:     list[int],
) -> ir.Value:
    """
    Allocate a null-terminated UTF-8 string as a module-level global constant.
    Returns a GEP pointer to byte[0] — valid C string pointer (i8*).
    """
    encoded  = (s + "\0").encode("utf-8")
    arr_type = ir.ArrayType(_i8, len(encoded))
    name     = f".str.{counter[0]}"
    counter[0] += 1

    g = ir.GlobalVariable(module, arr_type, name=name)
    g.global_constant = True
    g.linkage         = "internal"
    g.initializer     = ir.Constant(arr_type, bytearray(encoded))

    zero = ir.Constant(_i32, 0)
    return builder.gep(g, [zero, zero], inbounds=True)


# ─── Argument extraction (mirrors interpreter._extract_args) ─────────────────

def _extract_args(arglist_node: Tree | None) -> dict:
    """Direct-children iteration, consistent with interpreter._extract_args."""
    if arglist_node is None:
        return {}
    args: dict = {}
    for argument in arglist_node.children:
        if not (isinstance(argument, Tree) and argument.data == "argument"):
            continue
        name_node  = _first_tree_child(argument, "arg_name")
        value_node = _first_tree_child(argument, "arg_value")
        name       = str(name_node.children[0])
        vt         = value_node.children[0]
        tok_type   = getattr(vt, "type", "")
        if tok_type == "STRING":
            args[name] = str(vt)[1:-1]
        elif tok_type == "INTEGER":
            args[name] = int(str(vt))
        else:
            args[name] = str(vt)
    return args


# ─── Tree helpers ─────────────────────────────────────────────────────────────

def _first_tree_child(node: Tree, rule_name: str) -> Tree:
    for child in node.children:
        if isinstance(child, Tree) and child.data == rule_name:
            return child
    raise AssertionError(f"Expected child '{rule_name}' in '{node.data}'.")


def _get_str_field(node: Tree, field_name: str) -> str:
    """Extract the STRING token value from a header field node."""
    field = _first_tree_child(node, field_name)
    for child in field.children:
        if hasattr(child, "type") and child.type == "STRING":
            return str(child)[1:-1]
    raise AssertionError(f"No STRING token in '{field_name}'.")


# ─── CLI ──────────────────────────────────────────────────────────────────────

def _main() -> None:
    """
    Usage: python ir_generator.py <script.jky> [output.ll]

    Full pipeline: parse → validate → generate IR.
    Writes to output.ll if provided, otherwise prints to stdout.
    """
    _here = Path(__file__).resolve().parent
    _lxp  = _here.parent / "lexer_parser"
    for p in [str(_here), str(_lxp)]:
        if p not in sys.path:
            sys.path.insert(0, p)

    from parser    import JockyParseError, parse_file
    from validator import JockyValidationError, validate

    if len(sys.argv) not in (2, 3):
        print("Usage: python ir_generator.py <script.jky> [output.ll]", file=sys.stderr)
        sys.exit(1)

    script_path = Path(sys.argv[1])
    out_path    = Path(sys.argv[2]) if len(sys.argv) == 3 else None

    if not script_path.exists():
        print(f"Error: file not found — {script_path}", file=sys.stderr)
        sys.exit(1)

    try:
        tree = parse_file(script_path)
    except JockyParseError as exc:
        print(f"Parse error:\n  {exc}", file=sys.stderr)
        sys.exit(1)

    try:
        validate(tree)
    except JockyValidationError as exc:
        print(f"Validation error:\n  {exc}", file=sys.stderr)
        sys.exit(1)

    context = context_from_tree(tree)
    ir_text = generate_ir(tree, context)

    if out_path:
        out_path.write_text(ir_text, encoding="utf-8")
        print(f"IR written to {out_path}  ({len(ir_text):,} bytes, "
              f"{ir_text.count(chr(10))} lines)")
    else:
        print(ir_text)


if __name__ == "__main__":
    _main()